import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],


  tutorialSidebar: [
    {
      type: 'category',
      label: 'История',
      items: [
          'article/intro',
          'article/iteration-1',
          'article/architecture-insight',
          'article/iteration-2',
          'article/iteration-3',
          'article/iteration-4',
          'article/iteration-5',
          'article/iteration-6',
          'article/iteration-7',
          'article/iteration-8-autorun-steps',
          'article/scenax-integration',
          'article/scenax-conclusion',
      ],
    },
  ],

};

export default sidebars;
